AWESOME BOOK PROJECT-ES6 MODULE
3nityGitHub/AWESOME-BOOK-ES6-MODULE pull request #1
Opened 2023-05-08 23:12 UTC by 3nityGitHub

## In This PR:
   - I created a new repo and initialize it with git.
   - I used npm init -y command to create package.json file.
   - I  added the index.html, index.css and index.js file. 
   - I created a module folder and refactored my script using arrow function and broke them down into modules
   - I downloaded the luxon library to enable me display the current date below the navigation bar by importing it as a module

2023-05-09 06:51 UTC, wayungi requested changes
Hi @3nityGitHub , 

![image](https://user-images.githubusercontent.com/99656687/234198503-c41d0396-d5b0-4466-8ed1-959de33796fa.png)


**Congratulations on the good job done so far!** 🤝 

There are some issues that you still need to work on to go to the next project but you are almost there! 😄 

## Highlights ⚡ ⚡ 
- [ ] All linter checks are passing ✔️ 
- [ ]  Correct GitHub flow ✔️ 
- [ ] Descriptive PR body ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 06:51 UTC, wayungi commented on README.md
> +
- [x] The live demo section should link to a deployed version of your project. Please include a link to your deployed project or delete this section if deployment is not a project requirement 🤝

2023-05-09 06:51 UTC, wayungi commented on Modules/bookSet.js
> +  }
- [ ] Classes should not be defined inside functions. Instead, its functions/methods are defined inside classes. Please refactor this. 😄

2023-05-09 06:51 UTC, wayungi commented on Modules/bookSet.js
> +
- [ ] You are required to refactor all your functions to **arrow functions**. Kindly change all your functions to es6 arrow function syntax 😄

2023-05-09 06:51 UTC, wayungi commented on Modules/bookSet.js
> +  newBook.displaylist();
- [ OPTIONAL] Please do not instantiate the **Book** class in the module where it is defined. modules are meant to be imported and instantiated in the file where they are imported 👍🏾

2023-05-10 21:50 UTC, levy002 approved these changes
## Hello @3nityGitHub 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Status: APPROVED :fire:  :fire: 

## Highlights
- App is working well :heavy_check_mark: 
- Implemented all suggested changes :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 01:27 UTC, merged